#!/bin/bash

if [[ -r ~/.makepkg.conf ]];then
    . ~/.makepkg.conf
else
    [[ -r /etc/makepkg.conf ]] && . /etc/makepkg.conf
fi

if [[ -n $PKGDEST ]];then
    pkgdir=$PKGDEST
else
    mk_pkgdir
fi

mk_pkgdir(){
	pkgdir=${rundir}/packages/${arch}
	if ! [[ -d ${pkgdir} ]];then
	    mkdir -pv ${pkgdir}
	fi
}

cp_profile_pkgs(){
    for pkg in $(cat ${profiledir}/$1.set); do
	cp_pkg $pkg
    done
}

cp_pkg(){
    msg2 "Copying $1 to ${pkgdir}"
    cd $1
    cp -v *.pkg.tar.xz ${pkgdir}
    cd ..
}

cp_pkgs(){
    msg "Copying packages ..."
    eval "case $1 in
	$profiles)
	    cp_profile_pkgs $1
	;;
	*)
	    cp_pkg $1
	;;
    esac"
    msg "Finished copying"
}

sign_pkgs(){
    cd ${pkgdir}
    signpkgs
    cd ..
}
