'\" t
.\"     Title: gvfs
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/29/2014
.\"    Manual: Conventions and miscellaneous
.\"    Source: gvfs
.\"  Language: English
.\"
.TH "GVFS" "7" "" "gvfs" "Conventions and miscellaneous"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gvfs \- GIO virtual file system
.SH "DESCRIPTION"
.PP
GIO provides a VFS API to GLib applications\&. It includes a \*(Aqlocal\*(Aq implementation using POSIX\&. gvfs provides implementations that go beyond that and allow to access files and storage using many protocols, such as ftp, http, sftp, dav, obexftp, etc\&. It also provides support for trash folders, for cd burning and for monitoring interesting devices and volumes on the computer\&.
.PP
Applications use gvfs indirectly, by means of GIO loading the gvfs module that implements the GIO extension points\&. The gvfs support for volume monitoring is included in a separate loadable module\&.
.PP
The actual gvfs implementation is distributed over a number of processes\&. None of these are expected to be started from the commandline, except for debugging purposes\&.
.PP
Main processes:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd \- the main gvfs daemon
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfs\-fuse\-daemon \- mounts gvfs as a fuse filesystem
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-metadata \- writes gvfs metadata
.RE
.sp
Volume monitors:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfs\-udisks2\-volume\-monitor \- a udisks\-based volume monitor
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfs\-afc\-volume\-monitor \- a volume monitor for Apple iPhone/iPod Touch devices
.RE
.sp
Mount backends:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-afc \- mounts iPhone/iPod touch volumes
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-afp \- mounts Apple Filing Protocol volumes
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-afp\-browse \- browses Apple Filing Protocol volumes
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-archive \- mounts archive files in various formats
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-burn \- provides a location for burning CDs
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-cdda \- mounts audio CDs
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-computer \- provides computer://
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-dav \- mounts DAV filesystems
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-dnssd \- browses dnssd
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-ftp \- mounts over FTP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-http \- mounts over HTTP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-localtest \- a test backend
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-network \- provides network://
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-obexftp \- mounts over obexftp
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-recent \- provides recent://
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-sftp \- mounts over sftp
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-smb \- mounts Windows Shares Filesystem volumes
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-smb\-browse \- browses Windows Shares Filesystem volumes
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gvfsd\-trash \- provides trash://
.RE
.sp
.SH "ENVIRONMENT"
.PP
\fBGIO_USE_VFS\fR
.RS 4
If set, specifies the GIO vfs implementation to use\&. Possible values include \*(Aqlocal\*(Aq and \*(Aqgvfs\*(Aq\&.
.RE
.PP
\fBGIO_USE_VOLUME_MONITOR\fR
.RS 4
If set, specifies the GIO volume monitor implementation to use\&. Possible values include \*(Aqunix\*(Aq, \*(AqGProxyVolumeMonitorUDisks2\*(Aq, as well as other native volume monitors that are described in the key files in
\fB$XDG_DATA_DIRS\fR/gvfs/remote\-volume\-monitors\&.
.RE
.SH "FILES"
.PP
\fB$XDG_DATA_DIRS\fR/gvfs/mounts
.RS 4
This directory contains key files describing mount daemons\&.
.RE
.PP
\fB$XDG_DATA_DIRS\fR/gvfs/remote\-volume\-monitors
.RS 4
This directory contains key files describing remote volume monitors\&.
.RE
.SH "SEE ALSO"
.PP
\m[blue]\fBGIO documentation\fR\m[]\&\s-2\u[1]\d\s+2,
\fBgvfsd\fR(1),
\fBgvfsd-fuse\fR(1),
\fBgvfsd-metadata\fR(1)
.SH "NOTES"
.IP " 1." 4
GIO documentation
.RS 4
\%http://developer.gnome.org/gio
.RE
