'\" t
.\"     Title: gvfs-mime
.\"    Author: Bastien Nocera <hadess@hadess.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/29/2014
.\"    Manual: User Commands
.\"    Source: gvfs
.\"  Language: English
.\"
.TH "GVFS\-MIME" "1" "" "gvfs" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gvfs-mime \- Get or set mime handlers
.SH "SYNOPSIS"
.HP \w'\fBgvfs\-mime\ \-\-query\ \fR\fB{MIMETYPE}\fR\ 'u
\fBgvfs\-mime \-\-query \fR\fB{MIMETYPE}\fR
.HP \w'\fBgvfs\-mime\ \-\-set\ \fR\fB{MIMETYPE}\fR\fB\ \fR\fB{HANDER}\fR\ 'u
\fBgvfs\-mime \-\-set \fR\fB{MIMETYPE}\fR\fB \fR\fB{HANDER}\fR
.SH "DESCRIPTION"
.PP
\fBgvfs\-mime\fR
can query information about applications that are registered to handle a mime\-type, or set the default handler for a mime\-type\&.
.PP
Gvfs obtains this information from the shared\-mime\-info database\&. The default handler is stored per\-user, in the file
\fB$XDG_DATA_HOME\fR/applications/mimeapps\&.list\&.
.PP
MIMETYPE should be a mime\-type such as text/plain or application/mbox\&. HANDLER should be the name of an existing desktop file such as gedit\&.desktop\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints a short help text and exits\&.
.RE
.PP
\fB\-\-query\fR
.RS 4
Query the handler for MIMETYPE\&.
.RE
.PP
\fB\-\-set\fR
.RS 4
Set the default handler for MIMETYPE to HANDLER\&.
.RE
.SH "EXIT STATUS"
.PP
On success 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\fBgvfs-open\fR(1),
\m[blue]\fBShared MIME\-Info specification\fR\m[]\&\s-2\u[1]\d\s+2
.SH "NOTES"
.IP " 1." 4
Shared MIME-Info specification
.RS 4
\%http://freedesktop.org/wiki/Specifications/shared-mime-info-spec
.RE
