'\" t
.\"     Title: gvfs-move
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/29/2014
.\"    Manual: User Commands
.\"    Source: gvfs
.\"  Language: English
.\"
.TH "GVFS\-MOVE" "1" "" "gvfs" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gvfs-move \- Copy files
.SH "SYNOPSIS"
.HP \w'\fBgvfs\-move\ \fR\fB[OPTION...]\fR\fB\ \fR\fB[SOURCE]\fR\fB\ \fR\fB[DEST]\fR\ 'u
\fBgvfs\-move \fR\fB[OPTION...]\fR\fB \fR\fB[SOURCE]\fR\fB \fR\fB[DEST]\fR
.HP \w'\fBgvfs\-move\ \fR\fB[OPTION...]\fR\fB\ \fR\fB[SOURCE...]\fR\fB\ \fR\fB[DIRECTORY]\fR\ 'u
\fBgvfs\-move \fR\fB[OPTION...]\fR\fB \fR\fB[SOURCE...]\fR\fB \fR\fB[DIRECTORY]\fR
.SH "DESCRIPTION"
.PP
\fBgvfs\-move\fR
moves a file from SOURCE to DEST, or multiple SOURCEs to DIRECTORY\&.
.PP
\fBgvfs\-move\fR
is similar to the traditional mv utility, but using gvfs locations instead of local files: for example you can use something like smb://server/resource/file\&.txt as location\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints a short help text and exits\&.
.RE
.PP
\fB\-T\fR, \fB\-\-no\-target\-directory\fR
.RS 4
Don\*(Aqt move into DEST even if it is a directory\&.
.RE
.PP
\fB\-p\fR, \fB\-\-progress\fR
.RS 4
Show progress\&.
.RE
.PP
\fB\-i\fR, \fB\-\-interactive\fR
.RS 4
Prompt before overwriting files\&.
.RE
.PP
\fB\-b\fR, \fB\-\-backup\fR
.RS 4
Backup existing destination files\&.
.RE
.SH "EXIT STATUS"
.PP
On success 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\fBmv\fR(1)
