'\" t
.\"     Title: gvfs-mkdir
.\"    Author: Alexander Larsson <alexl@redhat.com>>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/29/2014
.\"    Manual: User Commands
.\"    Source: gvfs
.\"  Language: English
.\"
.TH "GVFS\-MKDIR" "1" "" "gvfs" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gvfs-mkdir \- Create directories
.SH "SYNOPSIS"
.HP \w'\fBgvfs\-mkdir\ \fR\fB[OPTION...]\fR\fB\ \fR\fB[LOCATION...]\fR\ 'u
\fBgvfs\-mkdir \fR\fB[OPTION...]\fR\fB \fR\fB[LOCATION...]\fR
.SH "DESCRIPTION"
.PP
\fBgvfs\-mkdir\fR
creates directories\&.
.PP
\fBgvfs\-mkdir\fR
is similar to the traditional mkdir utility, but using gvfs locations instead of local files: for example you can use something like smb://server/resource/mydir as location\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints a short help text and exits\&.
.RE
.PP
\fB\-p\fR, \fB\-\-parent\fR
.RS 4
Create parent directories when necessary\&.
.RE
.SH "EXIT STATUS"
.PP
On success 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\fBmkdir\fR(1)
