'\" t
.\"     Title: gvfs-info
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/29/2014
.\"    Manual: User Commands
.\"    Source: gvfs
.\"  Language: English
.\"
.TH "GVFS\-INFO" "1" "" "gvfs" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gvfs-info \- Show information about files
.SH "SYNOPSIS"
.HP \w'\fBgvfs\-info\ \fR\fB[OPTION...]\fR\fB\ \fR\fB[LOCATION...]\fR\ 'u
\fBgvfs\-info \fR\fB[OPTION...]\fR\fB \fR\fB[LOCATION...]\fR
.SH "DESCRIPTION"
.PP
\fBgvfs\-info\fR
shows information about the given locations\&.
.PP
\fBgvfs\-info\fR
is similar to the traditional ls utility, but using gvfs locations instead of local files: for example you can use something like smb://server/resource/file\&.txt as location\&.
.PP
File attributes can be specified with their gvfs name, e\&.g\&. standard::icon, or just by namespace, e\&.g\&. unix, or by \*(Aq*\*(Aq which matches all attributes\&. Several attributes or groups can be specified, separated by comma\&.
.PP
By default,
\fBgvfs\-info\fR
shows all attributes\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints a short help text and exits\&.
.RE
.PP
\fB\-w\fR, \fB\-\-query\-writable\fR
.RS 4
Show writable attributes and their types\&.
.RE
.PP
\fB\-f\fR, \fB\-\-filesystem\fR
.RS 4
Show information about the filesystem on which the files reside\&.
.RE
.PP
\fB\-a\fR, \fB\-\-attributes=ATTRIBUTES\fR
.RS 4
The attributes to get, specified as a comma\-separated list of gvfs file attribute names\&.
.RE
.PP
\fB\-n\fR, \fB\-\-nofollow\-symlinks\fR
.RS 4
Don\*(Aqt follow symlinks\&.
.RE
.SH "EXIT STATUS"
.PP
On success 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\fBls\fR(1),
\fBgvfs-ls\fR(1),
\m[blue]\fBGIO file attributes\fR\m[]\&\s-2\u[1]\d\s+2
.SH "NOTES"
.IP " 1." 4
GIO file attributes
.RS 4
\%http://developer.gnome.org/gio/2.32/gio-GFileAttribute.html
.RE
