_svc="net.lo"
_rlvl="boot"

post_install() {
  rc-update add ${_svc} ${_rlvl}
  rc-update -u
  echo
  cat <<MSG
	ATTENTION:
	The network configuration scripts will use dhcp by
	default to set up your interfaces.
	If you need to set up something more complete, see
	/usr/share/doc/netifrc*/README
MSG
	true
}

post_upgrade() {
  post_install "$1"
}

post_remove() {
  rc-update del ${_svc} ${_rlvl}
  rc-update -u
}
