svc="networkmanager"
rlvl="default"

post_install() {
	_cmd="rc-update add $svc $rlvl"
	echo "	==> run '$_cmd'"
}

post_upgrade() {
	post_install "$1"
  (( $(vercmp 0.8.3 $2) > 0 )) && cat <<MSG
ATTENTION:
  /etc/NetworkManager/nm-system-settings.conf has been replaced
  by /etc/NetworkManager/NetworkManager.conf. Make sure you move
  any custom settings to the new config file.
MSG
  true	
}

post_remove() {
	_cmd="rc-update del $svc $rlvl"
	echo "	==> run '$_cmd'"
}
