post_install() {
    getent group polkitd || groupadd -g 102 polkitd
    getent passwd polkitd || useradd -c 'Policy Kit Daemon' -u 102 -g polkitd -G proc -d '/' -s /usr/bin/nologin polkitd
    passwd -l polkitd &>/dev/null
}

post_upgrade() {
    post_install

    if (( $(vercmp $2 0.113-6) < 0 )); then
        usermod -aG proc -s /usr/bin/nologin polkitd
        chown root:102 /{etc,usr/share}/polkit-1/rules.d
        chmod 750 /{etc,usr/share}/polkit-1/rules.d
    fi
}
