_service="udev"
_rlvl="sysinit"

post_install() {
	_cmd="rc-update add $_service $_rlvl"
	$_cmd
	_cmd="rc-update add $_service-mount $_rlvl"
	$_cmd
}

post_upgrade() {
	post_install "$1"
	cat <<MSG
	ATTENTION:
	The loopback interface has been moved to netifrc package. 
	If you have services which do not start because of this,
	they can be fixed by adding rc_need=\"!net\""
	to the /etc/conf.d/<servicename> file.
MSG
	true
}

post_remove() {
	_cmd="rc-update del $_service $_rlvl"
	$_cmd
	_cmd="rc-update del $_service-mount $_rlvl"
	$_cmd
}
