_service="udev"
_rlvl="sysinit"

post_install() {
	_cmd="rc-update add $_service $_rlvl"
	$_cmd
	_cmd="rc-update add $_service-mount $_rlvl"
	$_cmd
}

post_upgrade() {
	post_install "$1"
	echo "The loopback interface has been moved to netifrc package,"
	echo "If you have services which do not start because of this,"
	echo "They can be fixed by adding rc_need=\"!net\""
	echo "to the /etc/conf.d/<servicename> file."
}

post_remove() {
	_cmd="rc-update del $_service $_rlvl"
	$_cmd
	_cmd="rc-update del $_service-mount $_rlvl"
	$_cmd
}
