_service="nfs"
_rlvl="default"

post_install() {
	_cmd="rc-update add $_service-openrc $_rlvl"
	echo "	==> run '$_cmd'"
	_cmd="rc-update add $_servicemount-openrc $_rlvl"
	echo "	==> run '$_cmd'"
}

post_upgrade() {
	post_install "$1"
}

post_remove() {
	_cmd="rc-update del $_service-openrc $_rlvl"
	echo "	==> run '$_cmd'"
	_cmd="rc-update del $_servicemount-openrc $_rlvl"
	echo "	==> run '$_cmd'"
}
