svc="lighttpd"
rlvl="default"

post_install() {
	conf1='server.pid-file = "/run/lighttpd.pid"'
	conf2='server.bind = "localhost"'
	file="/etc/lighttpd/lighttpd.conf"
	_usr=$svc
	_grp=$svc
	echo "	==>  requires $_usr user"
	echo "	==>  requires $_grp group"
	echo "	==>  $file requires $conf1"
	echo "	==>  $file requires $conf2(or any binding interface)"
	_cmd="rc-update add $svc $rlvl"
	echo "	==> run '$_cmd'"
}

post_upgrade() {
	post_install "$1"
}

post_remove() {
	_cmd="rc-update del $svc $rlvl"
	echo "	==> run '$_cmd'"
}
