svc="wicd"
rlvl="default"

post_install() {
	_cmd="rc-update add $svc $rlvl"
	echo "	==> run '$_cmd'"
	echo "To start wicd at boot, add /etc/init.d/wicd to a runlevel and:"
	echo "Remove all net.* initscripts (except for net.lo) from all runlevels"
	echo "Add these scripts to the RC_PLUGsvcS line in /etc/rc.conf"
	echo "(For example, rc_hotplug="!net.eth* !net.wlan*")"
}

post_upgrade() {
	post_install "$1"
}

post_remove() {
	_cmd="rc-update del $svc $rlvl"
	echo "	==> run '$_cmd'"
}
