#!/bin/bash 
# Copyright 2013 udeved@openrc4arch.site40.net
# Distributed under the terms of the GNU General Public License v2

check(){
	# $1: type
	# $2: file
	# $3: dirname
	if [ $1 = "init.d" ]; then
		rm_str "$2" '/var/run' '/run'
		case $3 in
			"dbus")
				mk_str $2 'dbus.pid' 'dbus/pid'
			;;
			"bind")
				mk_str $2 '/etc/bind/named.conf' '/etc/named.conf'
			;;
			"dhcp")
				if [ `basename $2 | grep "dhcpd"` ];then
					mk_str $2 '/etc/dhcp/${SVCNAME}' '/etc/${SVCNAME}' && \
					mk_str $2 '#@slapd@' 'ldap slapd'
				fi
 				if [ `basename $2 | grep "dhcrelay"` ];then
 					mk_str $2 '#@slapd@' 'ldap slapd'
 				fi
			;;
 			"ufw")	
				mk_str $2 '/usr/share/ufw/ufw-init-functions' '/usr/lib/ufw/ufw-init-functions'
			;;
			"xorg-server")
				if [ `basename $2 | grep "xdm.initd"` ];then
					rm_str $2 '/etc/profile.env' '/etc/profile' \
					&& mk_str $2 '/usr/bin/gdm' '/usr/sbin/gdm' && \
					rm_str $2 '{ROOTPATH}' '{PATH}'
				fi
			;;
			"mysql")
				mk_str $2 '/usr/bin/safe_mysqld' '/usr/bin/mysqld_safe'
			;;	
			"ntp")
				if [ `basename $2 | grep "ntpd"` ];then
					mk_str $2 '/usr/sbin/ntpd' '/usr/bin/ntpd'	
				fi
			;;	
			"openntpd")
				mk_str $2 '/usr/sbin/ntpd' '/usr/bin/ntpd'
			;;		
			"virtualbox-guest-additions")
				mk_str $2 'vboxguest-service' 'VBoxService' && \
				mk_str $2 '/usr/sbin/VBoxService' '/usr/bin/VBoxService'
			;;		
			"hostapd")
				mk_str $2 '/usr/sbin/hostapd' '/usr/bin/hostapd'
			;;
 			"cups")
 				mk_str "$2" '@neededservices@' 'need dbus avahi-daemon' && \
 				mk_str "$2" 'lp:lpadmin' 'daemon:sys'
 			;;
 			"openldap")
 				mk_str "$2" '/usr/lib/openldap/slapd' '/usr/lib/slapd'
 			;;
 			"subversion")
 				mk_str "$2" 'apache' 'http' && \
 				mk_str "$2" '/var/svn' '/srv/svn'
 			;;		
 			"mit-krb5")
 				if [ `basename $2 | grep "krb5kadmind"` ];then
					rm_str $2 'mit-krb5kdc' "krb5kdc"				
				fi
				if [ `basename $2 | grep "krb5kpropd"` ];then				
					mk_str $2 'mit-krb5kdc mit-krb5kadmind' "krb5kdc krb5kadmind"
				fi
 			;;
 			"vsftpd")
 				mk_str "$2" '/etc/vsftpd/${VSFTPD_NAME}.conf' '/etc/${VSFTPD_NAME}.conf' && \
 				mk_str $2 '/etc/vsftpd/vsftpd.conf' '/etc/vsftpd.conf'
 			;;
 			"squid")
 				mk_str "$2" 'chown squid' 'chown proxy'
 			;;
		esac	
		if [ "${PRE}" = "/usr" ]; then
			mk_str $2 '#!/sbin/runscript' "#!${PRE}/sbin/runscript"
			case $3 in
				"lvm2")
					if [ `basename $2 | grep "lvm"` ];then
						rm_str $2 '/bin/lvm /sbin/lvm' "${PRE}/bin/lvm ${PRE}/sbin/lvm"			
					fi
					if [ `basename $2 | grep "device-mapper"` ];then
						mk_str $2 '/sbin/dmsetup' "${PRE}/sbin/dmsetup"		
					fi
					if [ `basename $2 | grep "dmeventd"` ];then	
						mk_str $2 '/sbin/dmeventd' "${PRE}/sbin/dmeventd"
					fi
					if [ `basename $2 | grep "lvm-monitoring"` ];then	
						mk_str $2 '/sbin/vgchange' "${PRE}/sbin/vgchange" && \
						mk_str $2 '/sbin/vgs' "${PRE}/sbin/vgs"
					fi
				;;
				"rpcbind")
					mk_str $2 '/sbin/rpcbind' "${PRE}/bin/rpcbind"
				;;
				"iptables")
					mk_str $2 '"/sbin' '"/usr/sbin'
				;;
				"nfs-utils")
					if [ `basename $2 | grep "statd"` ];then
						mk_str $2 '/sbin/rpc.statd' "${PRE}/sbin/rpc.statd"
					fi
				;;
			esac
		fi
	else
		case $3 in
			"git")
				mk_str $2 '/var/git' '/srv/git'
			;;
			"subversion")
				mk_str $2 '/var/svn' '/srv/svn'
			;;
			"dhcp")
				if [ `basename $2 | grep "dhcpd.conf"` ];then
					mk_str $2 '/etc/dhcp/dhcpd.conf' '/etc/dhcpd.conf'
				fi	
			;;
		esac
	fi	
}
