#!/bin/bash 
# Author: udeved@openrc4arch.site40.net

. /etc/lsb-release

version="1.1.1" #"$(date +%Y%m%d)"
datadir="openrc-plugins-$version"
ext="xz"

mkdirs() {
	mkdir -p "${datadir}/$1"
}

download() {
	# $1: file
	# $2: src
	if [ ! -f "$1" ]; then
		curl -o "$1" "$2"
	fi
}

fix() {
	# $1: filename
	# $2: pattern1
	# $3: pattern2
	if grep -q "$2" $1; then
		echo "FAIL" 
		echo "fixing $1 ... $3 ..."
		sed -i "s|$2|$3|" $1
		echo "DONE" 
	else
		echo "PASS" $1 $3
	fi
}

config() {
	# $1: cfg file
	# $2: type
	setdist
	while read line; do
		local OIFS=$IFS
		local IFS='/'
		local arr=($line)
		local dirname=${arr[1]}
		local filename=${arr[3]}
		IFS=$OIFS
		
		mkdirs "$dirname/$2"
		
		local url="http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86"
		
		local file="${datadir}/${dirname}/$2/${filename}"
		local src="${url}/${line}"
		
		download "${file}" "${src}"
		
		if [ "$2" = "init.d" ]; then
		
			if [ $pref = "/usr" ]; then
			
				fix $file '#!/sbin/runscript' "#!$pref/sbin/runscript"
				
				fix $file '/var/run' '/run'
				
					if [ "$dirname" == "dbus" ]; then
						fix $file 'pidfile /run/dbus.pid' 'pidfile /run/dbus/pid'
					
					elif [ "$dirname" == "bind" ]; then
						fix $file '/etc/bind/named.conf' '/etc/named.conf'
					
					elif [ "$dirname" == "dhcp" ]; then
						fix $file '/etc/dhcp/${SVCNAME}' '/etc/${SVCNAME}'
					
					elif [ "$dirname" == "lvm2" ]; then
						fix $file '/bin/lvm /sbin/lvm' "$pref/bin/lvm $pref/sbin/lvm"	
						fix $file ' /sbin/dmsetup ' ' /usr/sbin/dmsetup '
						fix $file ' /sbin/dmeventd ' ' /usr/sbin/dmeventd '
					
					elif [ "$dirname" == "ntp" ]; then
						fix $file '/usr/sbin/ntpd' '/usr/bin/ntpd'	
				
					elif [ "$dirname" == "openntpd" ]; then
						fix $file '/usr/sbin/ntpd' '/usr/bin/ntpd'
				
					elif [ "$dirname" == "rpcbind" ]; then
						fix $file '/sbin/rpcbind' "$pref/bin/rpcbind"
						
					elif [ "$dirname" == "ufw" ]; then
						fix $file '/usr/share/ufw/ufw-init-functions' '/usr/lib/ufw/ufw-init-functions'
					
					elif [ "$dirname" == "xorg-server" ]; then
						fix $file '/etc/profile.env' '/etc/profile'
						fix $file 'ROOTPATH' 'PATH'
				
					elif [ "$dirname" == "iptables" ]; then
						fix $file 'iptables_bin="/sbin' 'iptables_bin="/usr/sbin'
					
					elif [ "$dirname" == "mysql" ]; then
						fix $file '/usr/bin/safe_mysqld' '/usr/bin/mysqld_safe'
				fi
			else
				
				fix $file '/var/run' '/run'
				
					if [ $dirname = "dbus" ]; then
						fix $file 'pidfile /run/dbus.pid' 'pidfile /run/dbus/pid'
					
					elif [ $dirname = "bind" ]; then
						fix $file '/etc/bind/named.conf' '/etc/named.conf'
					
					elif [ $dirname = "dhcp" ]; then
						fix $file '/etc/dhcp/${SVCNAME}' '/etc/${SVCNAME}'
					
					elif [ $dirname = "ntp" ]; then
						fix $file '/usr/sbin/ntpd' '/usr/bin/ntpd'	
				
					elif [ $dirname = "openntpd" ]; then
						fix $file '/usr/sbin/ntpd' '/usr/bin/ntpd'
				
					elif [ $dirname = "rpcbind" ]; then
						fix $file '/sbin/rpcbind' "$pref/bin/rpcbind"
						
					elif [ $dirname = "ufw" ]; then
						fix $file '/usr/share/ufw/ufw-init-functions' '/usr/lib/ufw/ufw-init-functions'
					
					elif [ $dirname = "xorg-server" ]; then
						fix $file '/etc/profile.env' '/etc/profile'
						fix $file 'ROOTPATH' 'PATH'
					
					elif [ $dirname = "mysql" ]; then
						fix $file '/usr/bin/safe_mysqld' '/usr/bin/mysqld_safe'
					fi
			fi
		fi	
	done < $1
}

setdist(){
	if [ "$DISTRIB_DESCRIPTION" == "Arch Linux" ];then
		pref="/usr"
	else
		pref=""
	fi
}

main(){	
	config "confd.cfg" "conf.d"
	config "initd.cfg" "init.d"
	
	#tar -cvjf "${datadir}.tar.${ext}"  ${datadir}/${dirname}
}
