#!/bin/bash 
# Author: udeved@openrc4arch.site40.net

. /etc/lsb-release

VER=0.1 #"$(date +%Y%m%d)"
PKGNAME='openrc-plugins'
DATADIR="${PKGNAME}"
EXT="xz"
PRE=""

mkdirs() {
	mkdir -p "${DATADIR}/$1"
}

download() {
	# $1: file
	# $2: src
	if [ ! -f "$1" ]; then
		echo "DOWLOADING" $2
		echo
		curl -o "$1" "$2"
		echo
		echo "DONE" $1
		echo
	fi
}

fix() {
	# $1: filename
	# $2: pattern1
	# $3: pattern2
	if ! grep -Fq "$3" $1; then
		echo "FAIL" `basename $1` $2
		echo
		echo "FIXING ..."
		sed  -e "s|$2|$3|" -i $1
		echo
		echo "DONE" `basename $1` $3
	else
		echo "PASS" `basename $1` $3
	fi
}

check(){
	# $1: type
	# $2: file
	# $3: dirname
	if [ "$1" = "init.d" ]; then
		
		fix $2 '/var/run' '/run'
		
		if [ "$3" = "dbus" ]; then
		
			fix $2 'dbus.pid' 'dbus/pid'
		
		elif [ "$3" = "bind" ]; then
			
			fix $2 '/etc/bind/named.conf' '/etc/named.conf'
		
		elif [ "$3" = "dhcp" ]; then
			
			if [ `basename $2 | grep "dhcpd"` ];then
			
				fix $2 '/etc/dhcp/${SVCNAME}' '/etc/${SVCNAME}'
			
			fi
		
		elif [ "$3" = "ufw" ]; then
			
			fix $2 '/usr/share/ufw/ufw-init-functions' '/usr/lib/ufw/ufw-init-functions'
		
		elif [ "$3" = "xorg-server" ]; then
		
			if [ `basename $2 | grep "xdm.initd"` ];then
				fix $2 '/etc/profile.env' '/etc/profile'
				fix $2 'ROOTPATH' 'PATH'
			fi
		
		elif [ "$3" = "mysql" ]; then
			
			fix $2 '/usr/bin/safe_mysqld' '/usr/bin/mysqld_safe'
		
		elif [ "$3" = "ntp" ]; then
			
			if [ `basename $2 | grep "ntpd"` ];then
				fix $2 '/usr/sbin/ntpd' '/usr/bin/ntpd'	
			fi
			
		elif [ "$3" = "openntpd" ]; then
			
			fix $2 '/usr/sbin/ntpd' '/usr/bin/ntpd'
		
		fi
		
		if [ "${PRE}" = "/usr" ]; then
			
			fix $2 '#!/sbin/runscript' "#!${PRE}/sbin/runscript"
			
			if [ "$3" = "lvm2" ]; then
				
				if [ `basename $2 | grep "lvm"` ];then
					fix $2 '/bin/lvm /sbin/lvm' "${PRE}/bin/lvm ${PRE}/sbin/lvm"
				fi
				
				if [ `basename $2 | grep "device-mapper"` ];then
					fix $2 '/sbin/dmsetup' "${PRE}/sbin/dmsetup"
				fi
				
				if [ `basename $2 | grep "dmeventd"` ];then				
					fix $2 '/sbin/dmeventd' "${PRE}/sbin/dmeventd"
				fi
				
			elif [ "$3" = "rpcbind" ]; then
				
				fix $2 '/sbin/rpcbind' "${PRE}/bin/rpcbind"
			
			elif [ "$3" = "iptables" ]; then
			
				fix $2 '"/sbin' '"/usr/sbin'
			
			fi
		fi
	fi	
}

setdist(){
	if [ "$DISTRIB_DESCRIPTION" = "Arch Linux" ];then
		PRE="/usr"
	else
		PRE=""
	fi
}

config() {
	# $1: cfg file
	# $2: type
	
	while read line; do
		local OIFS=$IFS
		local IFS='/'
		local arr=($line)
		local dirname=${arr[1]}
		local filename=${arr[3]}
		IFS=$OIFS
		mkdirs "$dirname/$2"
		local url="http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86"
		local file="${DATADIR}/${dirname}/$2/${filename}"
		local src="${url}/${line}"
		download "${file}" "${src}"
		check "$2" "${file}" "${dirname}"
	done < $1
}

main(){	
	setdist
	config "confd.list" "conf.d"
	config "initd.list" "init.d"
	tar -cvjf "${DATADIR}-${VER}.tar.${EXT}"  ${DATADIR}/${dirname}
}
