#!/bin/bash 
# Author: udeved@openrc4arch.site40.net

. ./pkg.cfg



fix_file() {
	# $1: file
	# $2: pattern1
	# $3: pattern2
	echo
	echo "checking `basename $1` ..."
	echo
	if ! grep -Fxq "$3" "$1"; then
		echo "${dist} FAIL"	
		echo
		echo "fixing..."
		echo "$2 --> $3"
		sed -i "s|$2|$3|g" "$1"
		echo "done"
	else
		echo "${dist} OK"	
	fi
}

mk_dirs() {
	mkdir -p "${datadir}/$1"
}

mk_pkg() {
	# $1: cfg file
	# $2: type
	while read line; do
		local OIFS=$IFS
		local IFS='/'
		local arr=($line)
		local dirname=${arr[1]}
		local filename=${arr[3]}
		IFS=$OIFS
		mk_dirs "$dirname/$2"
		local url="http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86"
		local file="${datadir}/${dirname}/$2/${filename}"
		local src="${url}/${line}"
		if [ ! -f "${file}" ]; then
			echo ${src}
			curl -o "${file}" "${src}"
			echo ${file}
		fi
		if [ "$2" = "init.d" ]; then
			fix_file "${file}" "#!/sbin/runscript" "#!/usr/sbin/runscript" 
		fi
		#echo
		#echo "archiving ${dirname} ..."
		#echo
		#tar -cvjf "${pkgdir}/${dirname}-${version}.tar.${ext}" -C "${datadir}" ${dirname}
		#echo
		#echo "${dirname}-${version}.tar.${ext} done"
	done < $1
}

run(){	
	#mkdir -p $pkgdir
	
	mk_pkg "confd.cfg" "conf.d"
	mk_pkg "initd.cfg" "init.d"
	
	tar -cvjf "${datadir}-${version}.tar.${ext}"  ${datadir}/${dirname}
}

run
