#!/bin/bash 
# Copyright 2013 udeved@openrc4arch.site40.net
# Distributed under the terms of the GNU General Public License v2

. ./functions

if [[ -e '/etc/lsb-release' ]];then
	. /etc/lsb-release
else
	DISTRIB_ID="unknown"
fi

VER=0.5
PKGNAME='openrc-plugins'
EXT="xz"
PRE=""

main(){	
	set_dist
	setup "confd.list" "conf.d"
	setup "initd.list" "init.d"
	#mk_tar
}

main
