#!/bin/bash 
# Copyright 2013 udeved@openrc4arch.site40.net
# Distributed under the terms of the GNU General Public License v2

if [[ -e '/etc/lsb-release' ]];then
	. /etc/lsb-release
else
	DISTRIB_ID="unknown"
fi

. ./functions

VER=0.9.4
PKGNAME='openrc-plugins'
EXT="xz"

main(){	
	set_prefix
	setup "confd.list" "conf.d"
	setup "initd.list" "init.d"
	set_version
	mk_tar
}

main
