/* Generated by dbus-binding-tool; do not edit! */


#ifndef __dbus_glib_marshal_up_daemon_MARSHAL_H__
#define __dbus_glib_marshal_up_daemon_MARSHAL_H__

#include	<glib-object.h>

G_BEGIN_DECLS

#ifdef G_ENABLE_DEBUG
#define g_marshal_value_peek_boolean(v)  g_value_get_boolean (v)
#define g_marshal_value_peek_char(v)     g_value_get_schar (v)
#define g_marshal_value_peek_uchar(v)    g_value_get_uchar (v)
#define g_marshal_value_peek_int(v)      g_value_get_int (v)
#define g_marshal_value_peek_uint(v)     g_value_get_uint (v)
#define g_marshal_value_peek_long(v)     g_value_get_long (v)
#define g_marshal_value_peek_ulong(v)    g_value_get_ulong (v)
#define g_marshal_value_peek_int64(v)    g_value_get_int64 (v)
#define g_marshal_value_peek_uint64(v)   g_value_get_uint64 (v)
#define g_marshal_value_peek_enum(v)     g_value_get_enum (v)
#define g_marshal_value_peek_flags(v)    g_value_get_flags (v)
#define g_marshal_value_peek_float(v)    g_value_get_float (v)
#define g_marshal_value_peek_double(v)   g_value_get_double (v)
#define g_marshal_value_peek_string(v)   (char*) g_value_get_string (v)
#define g_marshal_value_peek_param(v)    g_value_get_param (v)
#define g_marshal_value_peek_boxed(v)    g_value_get_boxed (v)
#define g_marshal_value_peek_pointer(v)  g_value_get_pointer (v)
#define g_marshal_value_peek_object(v)   g_value_get_object (v)
#define g_marshal_value_peek_variant(v)  g_value_get_variant (v)
#else /* !G_ENABLE_DEBUG */
/* WARNING: This code accesses GValues directly, which is UNSUPPORTED API.
 *          Do not access GValues directly in your code. Instead, use the
 *          g_value_get_*() functions
 */
#define g_marshal_value_peek_boolean(v)  (v)->data[0].v_int
#define g_marshal_value_peek_char(v)     (v)->data[0].v_int
#define g_marshal_value_peek_uchar(v)    (v)->data[0].v_uint
#define g_marshal_value_peek_int(v)      (v)->data[0].v_int
#define g_marshal_value_peek_uint(v)     (v)->data[0].v_uint
#define g_marshal_value_peek_long(v)     (v)->data[0].v_long
#define g_marshal_value_peek_ulong(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_int64(v)    (v)->data[0].v_int64
#define g_marshal_value_peek_uint64(v)   (v)->data[0].v_uint64
#define g_marshal_value_peek_enum(v)     (v)->data[0].v_long
#define g_marshal_value_peek_flags(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_float(v)    (v)->data[0].v_float
#define g_marshal_value_peek_double(v)   (v)->data[0].v_double
#define g_marshal_value_peek_string(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_param(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_boxed(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_pointer(v)  (v)->data[0].v_pointer
#define g_marshal_value_peek_object(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_variant(v)  (v)->data[0].v_pointer
#endif /* !G_ENABLE_DEBUG */


/* NONE:POINTER */
#define dbus_glib_marshal_up_daemon_VOID__POINTER	g_cclosure_marshal_VOID__POINTER
#define dbus_glib_marshal_up_daemon_NONE__POINTER	dbus_glib_marshal_up_daemon_VOID__POINTER

G_END_DECLS

#endif /* __dbus_glib_marshal_up_daemon_MARSHAL_H__ */

#include <dbus/dbus-glib.h>
static const DBusGMethodInfo dbus_glib_up_daemon_methods[] = {
  { (GCallback) up_daemon_enumerate_devices, dbus_glib_marshal_up_daemon_NONE__POINTER, 0 },
  { (GCallback) up_daemon_get_display_device, dbus_glib_marshal_up_daemon_NONE__POINTER, 60 },
  { (GCallback) up_daemon_get_critical_action, dbus_glib_marshal_up_daemon_NONE__POINTER, 118 },
};

const DBusGObjectInfo dbus_glib_up_daemon_object_info = {  1,
  dbus_glib_up_daemon_methods,
  3,
"org.freedesktop.UPower\0EnumerateDevices\0A\0devices\0O\0F\0N\0ao\0\0org.freedesktop.UPower\0GetDisplayDevice\0A\0device\0O\0F\0N\0o\0\0org.freedesktop.UPower\0GetCriticalAction\0A\0action\0O\0F\0N\0s\0\0\0",
"org.freedesktop.UPower\0DeviceAdded\0org.freedesktop.UPower\0DeviceRemoved\0\0",
"org.freedesktop.UPower\0DaemonVersion\0daemon_version\0read\0org.freedesktop.UPower\0OnBattery\0on_battery\0read\0org.freedesktop.UPower\0LidIsClosed\0lid_is_closed\0read\0org.freedesktop.UPower\0LidIsPresent\0lid_is_present\0read\0org.freedesktop.UPower\0IsDocked\0is_docked\0read\0\0"
};

