if [ -f '/etc/conf.d/nfs-rc' ];then
	_service[0]="nfs-rc"
else
	_service[0]="nfs"
fi
_service[1]="nfsmount"

_rlvl="default"

post_install() {
	_cmd="rc-update add ${_service[0]} $_rlvl"
	echo "	==> run '$_cmd'"
	_cmd="rc-update add ${_service[1]} $_rlvl"
	echo "	==> run '$_cmd'"
}

post_upgrade() {
	post_install "$1"
}

post_remove() {
	_cmd="rc-update del ${_service[0]} $_rlvl"
	echo "	==> run '$_cmd'"
	_cmd="rc-update del ${_service[1]} $_rlvl"
	echo "	==> run '$_cmd'"
}
