'\" t
.\"     Title: upower
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: April 2008
.\"    Manual: upower
.\"    Source: upower
.\"  Language: English
.\"
.TH "UPOWER" "1" "April 2008" "upower" "upower"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
upower \- UPower command line tool
.SH "SYNOPSIS"
.HP \w'\fBupower\fR\ 'u
\fBupower\fR [\fB\-\-dump\fR] [\fB\-\-enumerate\fR] [\fB\-\-monitor\-detail\fR] [\fB\-\-monitor\fR] [\fB\-\-show\-info\fR] [\fB\-\-version\fR] [\fB\-\-wakeups\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
\fIupower\fR
is a simple command line client for the
\fBUPower\fR(7)
daemon\&. TODO: not fully documented\&.
.SH "OPTIONS"
.PP
\fB\-\-monitor\fR
.RS 4
Connect to the UPower daemon and print a line every time a power source is added, removed or changed\&.
.RE
.PP
\fB\-\-monitor\-detail\fR
.RS 4
Like
\fB\-\-monitor\fR
but prints the full details of the power source whenever an event happens\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Show help options\&.
.RE
.SH "AUTHOR"
.PP
Written by David Zeuthen
<davidz@redhat\&.com>
with a lot of help from many others\&.
.SH "BUGS"
.PP
Please send bug reports to either the distribution or the DeviceKit mailing list, see
\m[blue]\fB\%http://lists.freedesktop.org/mailman/listinfo/devkit-devel\fR\m[]
on how to subscribe\&.
.SH "SEE ALSO"
.PP
\fBupowerd\fR(8),
\fBUPower\fR(7),
