_service="svnserve"
_rlvl="default"

post_install() {
	_usr="svn"
	_grp="svnusers"
 	_rootdir="/srv/svn"
	echo "	==>  requires $_usr user"
	echo "	==>  requires $_grp group"
	echo "	==>  requires svn root $_rootdir "
	_cmd="rc-update add $_service $_rlvl"
	echo "	==> run '$_cmd'"
}

post_upgrade() {
	post_install "$1"
}

pre_remove() {
	_cmd="rc-update del $_service $_rlvl"
	echo "	==> run '$_cmd'"
}
